### ISSUE TITLE
poll command reaction

### ISSUE THREAD

**Issue by vLuckyyy** [gt-c/Simple-Discord.js-Command-Handler#8]
Hay i have problem with msg.react

my code:

const {MessageEmbed} = require("discord.js");

module.exports = {
    id: 'poll',
    aliases: ['ankieta'],
    exec: async function (call) {
        if (!call.args[0]) {
            const empty = new MessageEmbed()
                .setAuthor(`MultiSupport | Ankieta`, `https://github.com/vLuckyyy/Icons/blob/main/pngegg.png?raw=true`)
                .setThumbnail('https://github.com/vLuckyyy/Icons/blob/main/error.png?raw=true')
                .setDescription('Musisz podać treść ankiety!')
                .setTimestamp()
                .setFooter(call.message.member.displayName, call.message.author.displayAvatarURL({dynamic: true}));
            return call.message.channel.send({embeds: [empty]});
        }
        if (!call.args[1]) {
            const poll = call.args.slice(0).join(" ");
            const msg = new MessageEmbed()
                .setAuthor(`MultiSupport | Ankieta`, `https://github.com/vLuckyyy/Icons/blob/main/pngegg.png?raw=true`)
                .setThumbnail(`https://static-00.iconduck.com/assets.00/poll-icon-512x512-5zm3vjo5.png`)
                .setDescription(`${poll}`)
                .setTimestamp()
                .setFooter(call.message.member.displayName, call.message.author.displayAvatarURL({dynamic: true}));
            call.message.channel.send({embeds: [msg]});
            msg.react('✅')
            msg.react('❌')
        }
    }
}

error:

The poll command encountered an error:
TypeError: msg.react is not a function
    at exec (C:\Users\konta\Desktop\MultiSupport\commands\poll.js:25:17)
    at Client.<anonymous> (C:\Users\konta\Desktop\MultiSupport\node_modules\d.js-command-handler\src\index.js:192:59)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Betanoir** [comment]
@vLuckyyy the msg variable is a MessageEmbed, not a Message. If you wish to react to the original message, you should do the following:

```js
call.message.react('✅')
```

else, if you wish to react to the new message containing the embed, you should do the following:

```js
const msgEmbed = new MessageEmbed()
    .setAuthor('MultiSupport | Ankieta', 'https://github.com/vLuckyyy/Icons/blob/main/pngegg.png?raw=true')
    .setThumbnail('https://static-00.iconduck.com/assets.00/poll-icon-512x512-5zm3vjo5.png')
    .setDescription(`${poll}`)
    .setTimestamp()
    .setFooter(call.message.member.displayName, call.message.author.displayAvatarURL({ dynamic: true }));

const msg = await call.message.channel.send({ embeds: [msgEmbed] });

msg.react('✅')
msg.react('❌')
```
